image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip
    - .env/

before_script:
  - apt-get update
  - apt-get -y install graphviz libgraphviz-dev pkg-config
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - python -m venv .env
  - source .env/bin/activate
  - pip install -r requirements.txt

stages:
  - lint

lint:
  stage: lint
  script:
    - pip install flake8
    - flake8 --ignore=E501,E402 --exclude=.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg,.env
